<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQp3WXx4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQp3WXx4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQp3WXx4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQp3WXx4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQp3WXx4\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qp3WXx4',
    'container.build_id' => '1406b8c5',
    'container.build_time' => 1608066626,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQp3WXx4');
